# SPDX-License-Identifier: BSD-2-Clause
# X-SPDX-Copyright-Text: (c) Copyright 2024 Advanced Micro Devices, Inc.

name: "perform_build"

on:
  push:
  pull_request:
    types: [opened]

jobs:
  extract_branch_info:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      tcpdirectBranch: ${{ steps.tcpdirectBranch.outputs.branch }}
      onloadBranch: ${{ steps.onloadBranch.outputs.branch }}
      packetDrillBranch: ${{ steps.packetDrillBranch.outputs.branch }}
      tcpdirectRepo: ${{ steps.tcpdirectRepo.outputs.branch }}
      onloadRepo: ${{ steps.onloadRepo.outputs.branch }}
      packetDrillRepo: ${{ steps.packetDrillRepo.outputs.branch }}
    steps:
      - name: tcpdirect
        uses: actions/checkout@v4
        with:
          path: tcpdirect

      - name: Install yq
        run: |
           sudo apt-get update
           sudo apt-get install -y python3 python3-pip jq
           pip3 install yq

      - name: Extract TCPDirect branch name
        id: tcpdirectBranch
        run: echo "branch=master" >> "$GITHUB_OUTPUT"

      - name: Extract onload branch name
        id: onloadBranch
        run: echo "branch=$(yq -r '.products.Onload.version' < $GITHUB_WORKSPACE/tcpdirect/versions.yaml)" >> "$GITHUB_OUTPUT"

      - name: Extract packetDrill branch name
        id: packetDrillBranch
        run: echo "branch=$(yq -r '.products.Packetdrill.version' < $GITHUB_WORKSPACE/tcpdirect/versions.yaml)" >> "$GITHUB_OUTPUT"

      - name: Extract TCPDirect repository name
        id: tcpdirectRepo
        run: echo "branch=${{ github.repository }}" >> "$GITHUB_OUTPUT"

      - name: Extract onload repository name
        id: onloadRepo
        run: echo "branch=$(yq -r '.products.Onload.repo_source' < $GITHUB_WORKSPACE/tcpdirect/versions.yaml | sed -E -e 's/^\s*.*://g' -e 's/\.git$//g')" >> "$GITHUB_OUTPUT"

      - name: Extract packetDrill repository name
        id: packetDrillRepo
        run: echo "branch=$(yq -r '.products.Packetdrill.repo_source' < $GITHUB_WORKSPACE/tcpdirect/versions.yaml | sed -E -e 's/^\s*.*://g' -e 's/\.git$//g')" >> "$GITHUB_OUTPUT"

  perform_build_and_test:
    needs: extract_branch_info
    uses: ./.github/workflows/perform_build.yml
    with:
      onloadBranch: ${{ needs.extract_branch_info.outputs.onloadBranch }}
      onloadRepo: ${{ needs.extract_branch_info.outputs.onloadRepo }}
      tcpdirectBranch: ${{ needs.extract_branch_info.outputs.tcpdirectBranch }}
      tcpdirectRepo: ${{ needs.extract_branch_info.outputs.tcpdirectRepo }}
      packetdrillBranch: ${{ needs.extract_branch_info.outputs.packetDrillBranch }}
      packetdrillRepo: ${{ needs.extract_branch_info.outputs.packetDrillRepo }}
    secrets: inherit

