# SPDX-License-Identifier: BSD-2-Clause
# X-SPDX-Copyright-Text: (c) Copyright 2024 Advanced Micro Devices, Inc.

name: "perform_build"

on:
  workflow_call:
    inputs:
      onloadBranch:
        description: "Version of onload to be built against"
        default: "master"
        required: true
        type: string
      onloadRepo:
        description: "Onload repository to checkout"
        default: "Xilinx-CNS/onload"
        required: true
        type: string
      tcpdirectBranch:
        description: "Version of tcpdirect to build"
        default: "master"
        required: true
        type: string
      tcpdirectRepo:
        description: "Version of tcpdirect to build"
        default: "Xilinx-CNS/tcpdirect"
        required: true
        type: string
      packetDrillBranch:
        description: "Version of onload to be built against"
        default: "master"
        required: true
        type: string
      packetDrillRepo:
        description: "Version of onload to be built against"
        default: "Xilinx-CNS/packetdrill-tcpdirect"
        required: true
        type: string
    secrets:
      PAT:
        required: true


jobs:
  perform_build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: tcpdirect
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.tcpdirectRepo }}
          path: tcpdirect
          ref: ${{ inputs.tcpdirectBranch }}
          token: ${{ secrets.PAT }}

      - name: onload checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.onloadRepo }}
          path: onload
          ref: ${{ inputs.onloadBranch }}
          token: ${{ secrets.PAT }}

      - name: packetdrill checkout
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: ${{ inputs.packetDrillRepo }}
          path: packetdrill-tcpdirect
          ref: ${{ inputs.packetDrillBranch }}
          token: ${{ secrets.PAT }}

      - name: Install TCPDirect Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl

      - name: build
        run: |
          cd $GITHUB_WORKSPACE/tcpdirect
          ONLOAD_TREE=$GITHUB_WORKSPACE/onload NDEBUG=1 make -j $(nproc)

      - name: shim
        run: |
          cd $GITHUB_WORKSPACE/tcpdirect
          ONLOAD_TREE=$GITHUB_WORKSPACE/onload NDEBUG=1 ZF_DEVEL=1 TEST_THREAD_NAME=zf make -j $(nproc) shim

      - name: tests
        run: |
          cd $GITHUB_WORKSPACE/tcpdirect
          ONLOAD_TREE=$GITHUB_WORKSPACE/onload UT_OUTPUT=$GITHUB_STEP_SUMMARY NDEBUG=1 ZF_DEVEL=1 TEST_THREAD_NAME=zf make -j $(nproc) -k test
